version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL="${REDIS_URL}"
      - BASE_URL="${BASE_URL}"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
