version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - BASE_URL=http://localhost:8080

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
