services:
  - type: web
    name: url-shortener
    env: docker
    runtime: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BASE_URL
        value: https://url-shortener.onrender.com
      - key: REDIS_URL
        value: redis://redis:6379
    healthCheckPath: /
    port: 8080

  - type: redis
    name: url-shortener-redis
    plan: free
